export const top = [
  'Aatrox',
  'Camille',
  'Cassiopeia',
  "Cho'Gath",
  'Darius',
  'Dr.Mudno',
  'Fiora',
  'Gankplank',
  'Garen',
  'Gnar',
  'Gwen',
  'Hecarim',
  'Haimerdinger',
  'Illaoi',
  'Irelia',
  'Jax',
  'Jayce',
  "K'Sante",
  'Karma',
  'Kayle',
  'Kennen',
  'Kled',
  'Lilia',
  'Malphite',
  'Maokai',
  'Mordekaiser',
  'Nassus',
  'Olaf',
  'Ornn',
  'Pantheon',
  'Poppy',
  'Quin',
  'Renekton',
  'Rengar',
  'Riven',
  'Rumble',
  'Ryze',
  'Sett',
  'Shen',
  'Singed',
  'Sion',
  'Swain',
  'Sylas',
  'Teemo',
  'Tryndamere',
  'Urgot',
  'Vayne',
  'Vladimir',
  'Volibear',
  'Wukong',
  'Yasuo',
  'Yorick',
];

export const jungle = [
  'Amumu',
  "Bel'Veth",
  'Diana',
  'Dr.Mudno',
  'Ekko',
  'Elise',
  'Evelynn',
  'Fiddlesticks',
  'Gragas',
  'Graves',
  'Hecarim',
  'Ivern',
  'Jarvan IV',
  'Jax',
  'Karthus',
  'Kayn',
  "Kha'Zix",
  'Kindred',
  'Kled',
  'Lee Sin',
  'Lillia',
  'Nidalee',
  'Nocturne',
  'Nunu',
  'Olaf',
  'Poppy',
  'Rammus',
  "Rek'Sai",
  'Rengar',
  'Sejuani',
  'Sett',
  'Shaco',
  'Shyvana',
  'Skarner',
  'Taliyah',
  'Trundle',
  'Udyr',
  'Vi',
  'Warwick',
  'Wikong',
  'Xin Zhao',
  'Zac',
];
export const middle = [
  'Ahri',
  'Akali',
  'Akshan',
  'Anivia',
  'Annie',
  'Aurelion Sol',
  'Azir',
  'Cassiopea',
  'Corki',
  'Diana',
  'Ekko',
  'Fizz',
  'Galio',
  'Haimerdinger',
  'Irelia',
  'Jayce',
  'Kassadin',
  'Katarina',
  'LeBlanc',
  'Lissandra',
  'Lucian',
  'Lux',
  'Malphite',
  'Malzahar',
  'Neeko',
  'Oriana',
  'Pantheon',
  'Pyke',
  'Rumble',
  'Ryze',
  'Swain',
  'Sylas',
  'Syndra',
  'Taliyah',
  'Talon',
  'Twisted Fate',
  'Veigar',
  "Vel'Koz",
  'Vex',
  'Viktor',
  'Vladimir',
  'Xerath',
  'Yasuo',
  'Zed',
  'Ziggs',
  'Zilean',
  'Zoe',
];
export const bottom = [
  'Aphelios',
  'Ashe',
  'Caitlyn',
  'Cassiopea',
  'Draven',
  'Ezreal',
  'Jhin',
  'Jinx',
  "Kai'Sa",
  'Kalista',
  'Karthus',
  "Kog'Maw,",
  'Lucian',
  'Miss Fortune',
  'Nilah',
  'Senna',
  'Seraphine',
  'Sivir',
  'Swain',
  'Tahm Kench',
  'Tristana',
  'Twitch',
  'Varus',
  'Vayne',
  'Xayah',
  'Yasuo',
  'Zeri',
  'Ziggs',
];
export const support = [
  'Alistar',
  'Amumu',
  'Anivia',
  'Ashe',
  'Bard',
  'Blitzcrank',
  'Brand',
  'Braum',
  'Fiddlesticks',
  'Galio',
  'Haimerdinger',
  'Janna',
  'Karma',
  'Leona',
  'Lulu',
  'Lux',
  'Morgana',
  'Nami',
  'Nautilus',
  'Pantheon',
  'Poppy',
  'Pyke',
  'Rakan',
  'Renata Glasc',
  'Senna',
  'Seraphine',
  'Sett',
  'Shen',
  'Sona',
  'Soraka',
  'Swain',
  'Tahm Kench',
  'Taric',
  'Thresh',
  "Vel'Koz",
  'Xerarth',
  'Yuumi',
  'Zilean',
  'Zyra',
];

export const generateRandomChampions = () => {
  const topChampions = top[Math.floor(Math.random() * top.length)];
  const jungleChampions = jungle[Math.floor(Math.random() * jungle.length)];
  const midChampions = middle[Math.floor(Math.random() * middle.length)];
  const bottomChampions = bottom[Math.floor(Math.random() * bottom.length)];
  const supportChampions = support[Math.floor(Math.random() * support.length)];

  return { topChampions, jungleChampions, midChampions, bottomChampions, supportChampions };
};

export const getRandomChampionByRole = (role: string | string[]) => {
  const { topChampions, jungleChampions, midChampions, bottomChampions, supportChampions } =
    generateRandomChampions();
  switch (role) {
    case 'TOP':
      return topChampions;
    case 'JUNGLE':
      return jungleChampions;
    case 'MID':
      return midChampions;
    case 'BOTTOM':
      return bottomChampions;
    case 'SUPPORT':
      return supportChampions;
    default:
      return topChampions;
  }
};

// Export const topChampions = top[Math.floor(Math.random() * top.length)];
// export const jungleChampions = jungle[Math.floor(Math.random() * jungle.length)];
// export const midChampions = middle[Math.floor(Math.random() * middle.length)];
// export const bottomChampions = bottom[Math.floor(Math.random() * bottom.length)];
// export const supportChampions = support[Math.floor(Math.random() * support.length)];
